/*
 * main.c
 *
 * Created: 10/6/2025 7:11:20 PM
 *  Author: isacm
 */ 
#include <avr/io.h>
#include <util/delay.h>
#include <avr/interrupt.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <avr/pgmspace.h>

// Seccion para USART
#define F_CPU 16000000UL    // Frecuencia del reloj del micro (16 MHz)
#define BAUD 9600           // Velocidad de transmisión (baudios)
#define BRC ((F_CPU / 16 / BAUD) - 1)   // Valor para UBRR
#define TX_BUFFER_SIZE 128
#define RX_BUFFER_SIZE 128
#define precarger 10000

// Direcciones base
#define SOLENOID_DOWN   1
#define SOLENOID_UP     2
#define DOWN            3
#define UP              4
#define RIGHT           5
#define LEFT            6
#define STOP            7

// Diagonales 
#define UP_RIGHT        8
#define UP_LEFT         9
#define DOWN_RIGHT      10
#define DOWN_LEFT       11

// Direcciones base
#define SOLENOIDDOWN   1
#define SOLENOIDUP     2
#define DOWN            3
#define UP              4
#define RIGHT           5
#define LEFT            6
#define STOP            7

// Diagonales
#define UPRIGHT        8
#define UPLEFT         9
#define DOWNRIGHT      10
#define DOWNLEFT       11




volatile char    serialBuffer[TX_BUFFER_SIZE];
volatile uint8_t serialReadPos  = 0;
volatile uint8_t serialWritePos = 0;

volatile char    rxBuffer[RX_BUFFER_SIZE];
volatile uint8_t rxReadPos  = 0;
volatile uint8_t rxWritePos = 0;
volatile uint8_t CONTADOR = 0; 
volatile const uint8_t radio = 10; 

void appendSerial(char c);
void serialWrite(const char *c);
char peekChar(void);
char Chardos(void);


// macro para setear
#define sbi(sfr, bit) (_SFR_BYTE(sfr) |= _BV(bit))

// macro para resetear
#define cbi(sfr, bit) (_SFR_BYTE(sfr) &= ~_BV(bit))


void Subir(void);
void Bajar(void);
void Izquierda(void);
void Derecha(void);
void diagI_sup(void);
void diagI_inf(void);
void diagD_sup(void);
void diagD_inf(void);
void X(void);
void Y(void);

void centrar(void);
void peurbas(char c);
void dibujar_triangulo(void);
void dibujar_cuadrado(void);
void dibujar_cruz(void);
static inline void generar_escalon(uint16_t ang_deg, const uint16_t tR[91], const uint16_t tU[91]);
void Hacer_circulo(void);
void Hacer_circulo_lut(void);
void ejecutar_circulo(const uint8_t *tabla, uint16_t size);
	


const uint16_t Flor[] PROGMEM = {SOLENOID_DOWN,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,
	DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,
	LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,DOWN,DOWNLEFT,DOWN,
	DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,
	DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,
	DOWNLEFT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,
	DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNLEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,
	LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,
	UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,
	LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,DOWNLEFT,LEFT,UPLEFT,DOWNLEFT,
	LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,
	DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,
	LEFT,DOWNLEFT,LEFT,DOWNLEFT,DOWN,DOWNLEFT,LEFT,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,
	DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,
	DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,
	DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,
	DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,
	DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,
	DOWN,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,
	DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,
	RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,
	DOWNRIGHT,UPRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,DOWN,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,DOWN,DOWNLEFT,DOWN,
	DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,
	DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,
	DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,
	DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,
	DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,
	DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,
	RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,
	DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,
	RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,
	UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,
	RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,
	UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,
	UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,
	UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,DOWNRIGHT,DOWN,
	DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,
	DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,
	DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,
	DOWN,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,
	DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,
	RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,
	UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,
	RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,
	UPRIGHT,RIGHT,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,
	UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,
	UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UPLEFT,UPRIGHT,UP,UPLEFT,
	UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,
	UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,
	UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,LEFT,UPLEFT,LEFT,
	UPLEFT,LEFT,UPLEFT,UP,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,
	RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,
	UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,
	RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,
	UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,
	UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,
	UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,
	UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,
	UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,
	LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,
	UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,
	LEFT,UPLEFT,LEFT,UPLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,
	DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,
	LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,
	DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,UPLEFT,UPRIGHT,UP,UPRIGHT,
	UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,
	UPRIGHT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,
	UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,
	UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,
	LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,
	UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,
	LEFT,UPLEFT,LEFT,UPLEFT,SOLENOID_UP,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN, DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,DOWN,SOLENOID_DOWN,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,
		DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,
		LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,
		DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,
		DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,
		DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,
		DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,
		DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,
		RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,
		DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,UPRIGHT,
		RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,
		UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,
		RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,
		UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,
		UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPLEFT,UP,
		UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,
		UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,
		UPLEFT,UP,UPLEFT,UP,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,
		LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,
	UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,SOLENOID_UP};


const uint16_t Murcielago[] PROGMEM = {DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT,
	LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT,
	DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT,
	LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT,
	DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, DOWN, DOWNRIGHT,
	RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT,
	DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT,
	RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, DOWN,
	DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT,
	DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN,
	DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWNLEFT, DOWN, DOWNRIGHT, DOWNLEFT, DOWN, DOWNLEFT,
	DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN,
	DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT,
	RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT,
	DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT,
	RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN,
	DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT,
	DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN,
	DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT,
	RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT,
	UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT,
	RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT,
	DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT,
	RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN,
	DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT,
	DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, RIGHT, UPRIGHT, UP,
	UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT,
	UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP,
	UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT,
	RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT,
	UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT,
	RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT,
	DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT,
	RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP,
	UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT,
	UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP,
	UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT,
	RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT,
	UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT,
	RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, UP, UPRIGHT, UP, UPLEFT, UP, UPLEFT, UP,
	UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT,
	UP, UPLEFT, UP, UPLEFT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP,
	UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT,
	UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP,
	UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT,
	RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT,
	UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT,
	RIGHT, UPRIGHT, UP, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT,
	UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT,
	LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT,
	UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT,
	LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT,
	DOWNLEFT, LEFT, UPLEFT, LEFT, DOWNLEFT, UPLEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT,
	LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT,
	DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT,
	LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT,
	DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT,
	DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN,
	DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT,
	DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT,
	DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT,
	LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT,
	UPLEFT, LEFT, UPLEFT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT,
	UP, UPRIGHT, UP, UPLEFT, UP, UPRIGHT, UP, UPRIGHT, RIGHT, UPRIGHT, RIGHT, UPRIGHT, UP, UPRIGHT, UP,
	UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT,
	UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPRIGHT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP,
	UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, LEFT, UPLEFT,
	LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, DOWN, DOWNLEFT, DOWN,
	DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT,
	DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT,
	UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT,
	LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, LEFT, UPLEFT, UP,
	UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT,
	UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT,
	UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, DOWNLEFT, LEFT, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT,
	DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNLEFT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN,
	DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT,
	DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, RIGHT, DOWNRIGHT, RIGHT, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN,
	DOWNLEFT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNRIGHT, DOWN, DOWNLEFT,
	LEFT, DOWNLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT,
	UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT,
	LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP,
	UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT,
	UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP,
	UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT, UP, UPLEFT,
	UP, UPLEFT, UP, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT,
	UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT,
	LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT, UPLEFT, LEFT,
UPLEFT, LEFT, UPLEFT, LEFT, STOP};

const uint8_t CIRCLE_DATA[] PROGMEM = {
  SOLENOID_DOWN,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,
  DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,
  LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,LEFT,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,
  DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,
  DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,DOWNLEFT,DOWN,
  DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,
  DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,
  DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,DOWN,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,
  RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,
  DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,DOWNRIGHT,RIGHT,UPRIGHT,
  RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,
  UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,
  RIGHT,UPRIGHT,RIGHT,UPRIGHT,RIGHT,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,
  UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,
  UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPRIGHT,UP,UPLEFT,UP,
  UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,
  UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,UPLEFT,UP,
  UPLEFT,UP,UPLEFT,UP,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,
  LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,
  UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,LEFT,UPLEFT,SOLENOID_UP
	};



	
int main(void)
{
	
	UBRR0H = (BRC >> 8);
	UBRR0L = BRC;
	
	timer1_init_1ms();
	
	UCSR0B = (1 << TXEN0) | (1 << RXEN0) | (1 << RXCIE0);
	
	// Modo asincrónico, 8 bits, 1 stop, sin paridad
	UCSR0C = (1 << UCSZ01) | (1 << UCSZ00);
	
	sei();
	
	DDRB |= (1 << PORTB0);
 	DDRD = 0b11111110;
	
	
	
	serialWrite("\nSelecciona la figura a dibujar:\n");
	serialWrite("1 - Murcielago\n");
	serialWrite("2 - Flor\n");
	serialWrite("3 - Circulo\n");

	
	
	_delay_ms(5);
	
    while(1)
    {
	    char c = Chardos();
	    if (c != '\0') {
		    serialWrite("Recibido: ");
		    appendSerial(c);
		    appendSerial('\n');
	    }
	    
		
		int sx, sy;
					
	    if (c == '1') {
		    ejecutar_forma(Murcielago, sizeof(Murcielago));
	    }
		if (c == '2') {
			ejecutar_forma(Flor, sizeof(Flor));
					}
		if (c == '3') {
			Hacer_circulo2();
		}
		if (c == '4') {
			dibujar_triangulo();
		}
		if (c == '5') {
			dibujar_cruz();
		}
		if (c == '6') {
			Bajar();
			_delay_ms(300);
			Derecha();
			_delay_ms(300);
			dibujar_cruz();
			Derecha();
			_delay_ms(300);
		    ejecutar_forma(Murcielago, sizeof(Murcielago));
		    _delay_ms(300);
			ejecutar_forma(Flor, sizeof(Flor));
			_delay_ms(300);
			dibujar_triangulo();
			_delay_ms(300);
			ejecutar_forma(CIRCLE_DATA, sizeof(CIRCLE_DATA));
			
		}
	    else {
		    peurbas(c);
	    }
    }

    }
 
void timer1_init_1ms(void) {
	// CTC: WGM12 = 1, WGM13:0 = 0100
	TCCR1A = 0;
	TCCR1B = 0;
	TCCR1B |= (1 << WGM12);

	// OCR1A = F_CPU / (prescaler * 1000) - 1
	// Con prescaler 64 y F_CPU=16 MHz -> 16000000/64/1000 - 1 = 249
	OCR1A = (uint16_t)(F_CPU / 64UL / 1000UL - 1);

	// Arrancar con prescaler = 64 (CS11=1, CS10=1)
	TCCR1B |= (1 << CS11) | (1 << CS10);

	// Limpia cualquier bandera pendiente
	TIFR1 = (1 << OCF1A);
}

static inline void delay_ms_timer1(uint16_t ms) {
	while (ms--) {
		// Reinicia conteo y bandera
		TCNT1 = 0;
		TIFR1 = (1 << OCF1A);
		// Espera hasta que ocurra la comparación (1 ms)
		while ((TIFR1 & (1 << OCF1A)) == 0) { /* espera */ }
	}
}


// ---- Generar tablas seno/cos 0–90° ----
void precompute_semicirculo_arrays_90(uint16_t I_ms, uint16_t tR90[90], uint16_t tU90[90]) {
	for (uint16_t i = 0; i < 90; ++i) {
		float th = (float)i * (float)M_PI / 180.0f;
		float c = cosf(th);
		float s = sinf(th);
		if (c < 0) c = 0; else if (c > 1) c = 1;
		if (s < 0) s = 0; else if (s > 1) s = 1;
		tR90[i] = (uint16_t)lrintf(c * (float)I_ms);
		tU90[i] = (uint16_t)lrintf(s * (float)I_ms);
	}
}

void Hacer_circulo2(void) {
	delay_ms_timer1(100);
	cli();

	Subir_s(); // baja el lápiz (solenoide)

	uint16_t n = sizeof(CIRCLE_DATA); // bytes totales
	for (uint16_t i = 0; i + 1 < n; i += 2) { // avanza de a pares (tiempo, comando)
		uint8_t t   = pgm_read_byte(&CIRCLE_DATA[i]);     // tiempo en i
		uint8_t cmd = pgm_read_byte(&CIRCLE_DATA[i + 1]); // comando en i+1

		switch (cmd) {
			case UP:         Subir(); break;
			case DOWN:       Bajar(); break;
			case LEFT:       Izquierda(); break;
			case RIGHT:      Derecha(); break;
			case UP_RIGHT:   ArribaDerecha(); break;
			case DOWN_RIGHT: AbajoDerecha(); break;
			case DOWN_LEFT:  AbajoIzquierda(); break;
			case UP_LEFT:    ArribaIzquierda(); break;
			case SOLENOID_UP:   /* si lo agregás en la LUT */ apagar(); break;
			case SOLENOID_DOWN: /* si lo agregás en la LUT */ Subir_s(); break;
			default:         apagar(); break;
		}

		delay_ms_timer1(t);
		// opcional: un mini gap entre pasos
		// delay_ms_timer1(2);
	}

	apagar();
	sei();
	delay_ms_timer1(200);
}


// ---- Dibujar círculo completo ----
void Hacer_circulo(void) {
	const uint16_t I_ms = 90;      // Duración base de cada paso
	uint16_t tR90[90], tU90[90];   // Tablas seno/cos de 0–90°

	precompute_semicirculo_arrays_90(I_ms, tR90, tU90);

	delay_ms_timer1(100);
	cli();

	Subir_s();   // Baja el lápiz

	for (uint16_t ang = 0; ang < 360; ++ang) {
		uint16_t q = ang / 90;      // Cuadrante actual (0–3)
		uint16_t idx = ang % 90;    // Índice dentro del cuadrante (0–89)

		switch (q) {
			case 0: // Q1: UP + RIGHT
			Derecha();
			delay_ms_timer1(tU90[idx]);
			Subir();
			delay_ms_timer1(tR90[idx]);
			apagar2();
			_delay_ms(10);
			break;
	
			case 1: // Q2: DOWN + RIGHT
			Bajar();
			delay_ms_timer1(tU90[idx]);
			Derecha();
			delay_ms_timer1(tR90[idx]); 
			apagar2();
			_delay_ms(10);
			break;

			case 2: // Q3: DOWN + LEFT
			Izquierda();
			delay_ms_timer1(tU90[idx]);
			Bajar();
			delay_ms_timer1(tR90[idx]);
			apagar2();
			_delay_ms(10);
			break;

			case 3: // Q4: UP + LEFT
			Subir();
			delay_ms_timer1(tU90[idx]);
			Izquierda();
			delay_ms_timer1(tR90[idx]);
			apagar2();
			_delay_ms(10);
			break;
		}
	}

	apagar();   // Apaga motores
	sei();
	delay_ms_timer1(200);
}
 void dibujar_cruz(void){
	 Subir_s();
	 _delay_ms(500);
	 ArribaDerecha();
	 _delay_ms(24000);
	 AbajoIzquierda();
	 _delay_ms(12000);
	ArribaIzquierda();
	_delay_ms(12000);
	AbajoDerecha();
	_delay_ms(24000);
	 apagar();
	 
 }
 
 void dibujar_triangulo(void){
	
		Subir_s();
		_delay_ms(500);
		Bajar();   
		_delay_ms(27000); 
		ArribaDerecha();  
		_delay_ms(12000);
		ArribaIzquierda();   
		_delay_ms(12000);
		
		apagar();
		
 }
		
 void dibujar_cuadrado(void){
	 
	_delay_ms(100);
	 Subir_s();          
	 _delay_ms(100);
	CONTADOR = 0;
	
	
	 while (CONTADOR < 2) { Subir();     }   // 2 s
	 while (CONTADOR < 4) { Derecha();   }   // 2 s
	 while (CONTADOR < 6) { Bajar();     }   // 2 s
	 while (CONTADOR < 8) { Izquierda(); }   // 2 s
	 //x
	 
	  _delay_ms(100);
	 apagar();
	 _delay_ms(100);
	 
 }


void ejecutar_circulo_sinc(const uint8_t *tablaDir, const uint8_t *tablaTime, uint16_t size) {
	uint8_t cmd;
	uint8_t t;

	_delay_ms(1000);  // Espera inicial

	for (uint16_t i = 0; i < size; i++) {
		cmd = pgm_read_byte(&tablaDir[i]);   // dirección
		t   = pgm_read_byte(&tablaTime[i]);  // tiempo correspondiente

		if (cmd == STOP)
		break;

		// Ejecutar la acción según comando
		switch (cmd) {
			case UP:            Subir(); break;
			case DOWN:          Bajar(); break;
			case LEFT:          Izquierda(); break;
			case RIGHT:         Derecha(); break;

			case UP_LEFT:       ArribaIzquierda(); break;
			case UP_RIGHT:      ArribaDerecha(); break;
			case DOWN_LEFT:     AbajoIzquierda(); break;
			case DOWN_RIGHT:    AbajoDerecha(); break;

			case SOLENOID_UP:   apagar(); break;
			case SOLENOID_DOWN: Subir_s(); break;

			default:            apagar(); break;
		}

		for (uint8_t j = 0; j < t; j++) {
			_delay_ms(10);
		}

	}

	_delay_ms(1000);  // Espera final
	apagar();
}

void ejecutar_forma(const uint16_t *tablaDir, uint16_t size) {
	uint8_t cmd;

	_delay_ms(1000);  // Espera inicial

	for (uint16_t i = 0; i < size; i++) {
		cmd = pgm_read_byte(&tablaDir[i]);   // dirección
		

		if (cmd == STOP)
		break;

		// Ejecutar la acción según comando
		switch (cmd) {
			case UP:            Subir(); break;
			case DOWN:          Bajar(); break;
			case LEFT:          Izquierda(); break;
			case RIGHT:         Derecha(); break;

			case UPLEFT:       ArribaIzquierda(); break;
			case UPRIGHT:      ArribaDerecha(); break;
			case DOWNLEFT:     AbajoIzquierda(); break;
			case DOWNRIGHT:    AbajoDerecha(); break;

			case SOLENOID_UP:   apagar(); break;
			case SOLENOID_DOWN: Subir_s(); break;

			default:            apagar(); break;
		}
		_delay_ms(150);
	}

	_delay_ms(1000);  // Espera final
	apagar();
}

void peurbas(char c){
	switch (c) {
		case 'x': apagar(); break;
		case 's': Subir_s(); break;
		case 'u': Subir(); break;
		case 'd': Bajar(); break;
		case 'l': Izquierda(); break;
		case 'r': Derecha(); break;
		case 'z': AbajoIzquierda(); break;
		case 'c': AbajoDerecha(); break;
		case 'q': ArribaIzquierda(); break;
		case 'e': ArribaDerecha(); break;   
		case 'j': centrar(); break;
		default: break;
	}
}

void centrar(void){
	CONTADOR = 0;
	TCNT1H = 0xC2;
	TCNT1L = 0xF7;
	
	while(CONTADOR < 6){
		AbajoDerecha();
	}
	apagar();
}


void apagar(void){

PORTD = (PORTD & 0b00000011) | 0b00001000;

}

void apagar2(void){

	PORTD = (PORTD & 0b00001111) | 0b00000000;

}
void Subir_s(void)
{
PORTD = (PORTD & 0b00000011) | 0b00000100;


}

void Bajar(void)
{
PORTD = (PORTD & 0b00001111) | 0b00010000;
}

void Subir(void)
{
PORTD = (PORTD & 0b00001111) | 0b00100000;
}

void Izquierda(void)
{
PORTD = (PORTD & 0b00001111) | 0b01000000;
}


void Derecha(void)
{
PORTD = (PORTD & 0b00001111) | 0b10000000;
}

void AbajoIzquierda(void)
{
	PORTD = (PORTD & 0b00001111) | 0b01010000; // D6 y D4
}

void AbajoDerecha(void){
	PORTD = (PORTD & 0b00001111) | 0b10010000; // D6 y D4
}

void ArribaIzquierda(void)
{
	PORTD = (PORTD & 0b00001111) | 0b01100000; // D3 y D4
}

void ArribaDerecha(void){
	PORTD = (PORTD & 0b00001111) | 0b10100000; // D6 y D4
}


ISR(TIMER1_OVF_vect) {
	CONTADOR++;
	TCNT1H = 0xC2;
	TCNT1L = 0xF7;
}




void appendSerial(char c)
{
	serialBuffer[serialWritePos] = c;
	serialWritePos++;

	if (serialWritePos >= TX_BUFFER_SIZE) {
		serialWritePos = 0;   // wrap-around
	}
}
void serialWrite(const char *s){
	for (uint8_t i = 0; i < (uint8_t)strlen(s); i++){
		serialBuffer[serialWritePos] = s[i];
		serialWritePos = (serialWritePos + 1) % TX_BUFFER_SIZE;
	}
	UCSR0B |= (1 << UDRIE0);   // habilita ISR UDRE
}
ISR(USART_UDRE_vect){
	if (serialReadPos != serialWritePos){
		UDR0 = serialBuffer[serialReadPos];
		serialReadPos = (serialReadPos + 1) % TX_BUFFER_SIZE;
		} else {
		UCSR0B &= ~(1 << UDRIE0);  // nada más que enviar
	}
}
char peekChar(void)
{
	char ret = '\0';

	if (rxReadPos != rxWritePos)
	{
		ret = rxBuffer[rxReadPos];
	}

	return ret;
}
char Chardos(void)
{
	char ret = '\0';

	if (rxReadPos != rxWritePos)
	{
		ret = rxBuffer[rxReadPos];

		rxReadPos++;

		if (rxReadPos >= RX_BUFFER_SIZE)
		{
			rxReadPos = 0;
		}
	}

	return ret;
}
ISR(USART_RX_vect)
{
	rxBuffer[rxWritePos] = UDR0;

	rxWritePos++;

	if (rxWritePos >= RX_BUFFER_SIZE)
	{
		rxWritePos = 0;
	}
}



